{"uuid": "a6385f14-fa98-475d-ba6a-9a940e0cfaa9", "children": ["ad778465-37ed-4866-84d8-65c131c30c59"], "befores": [{"name": "ex_ap_ssid", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/lanforge/tkinter_1/pytest/pytest_trial/tests/conftest.py\", line 63, in ex_ap_ssid\n    allure.attach(name=\"EX-AP1 SSID\", body=var)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/allure_pytest/listener.py\", line 222, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/allure_commons/reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/lanforge/.local/lib/python3.8/site-packages/allure_commons/logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"name": "EX-AP1 SSID", "source": "cbb98f5f-fcab-42d8-b437-2c791b80fbf6-attachment.attach"}], "start": 1689613249067, "stop": 1689613249067}], "start": 1689613249067, "stop": 1689613249137}